add SCANF_ALT
DataCorrupted/function-embedding pull request #1
Opened 2022-11-29 02:47 UTC by EYH0602

text replace `scanf` to `SCANF_ALT` and print all variables to stdout.

2022-11-29 03:05 UTC, DataCorrupted requested changes

2022-11-29 03:05 UTC, DataCorrupted commented on encode2stdout.h
> +            char pfmt[10] = "%s %c %";                                                \
Can we change the separator from space(` `) to comma(`,`)?
The reason is caller of `scanf` may give you a statement, e.g. `&a + 2`, that would make our output un-separatable.
Sorry I didn't think about this before.

2022-11-29 07:04 UTC, DataCorrupted requested changes

2022-11-29 07:04 UTC, DataCorrupted commented on encode2stdout.h
> +            char pfmt[10] = "%s,%c,%";                \
- I would suggest you use C++ to deal with `pfmt`
- If you have to use C:
    -  Use memory aligned size(16, 32, 64, etc.)
    - Use `memset` to set the string to 0 first. Stack allocated memory may not be 0
    - Use `sprintf` instead of manually calculating offset.

2022-11-29 07:04 UTC, DataCorrupted commented on encode2stdout.h
> +    fprintf(stderr, pfmt, name_tokens[i], type_tokens[i], val)
It is not a good idea to use values defined outside macro , you may accidently capture values you do not intend to ([hygienic macro](https://en.wikipedia.org/wiki/Hygienic_macro))

Besides, if you do not intend for outsiders to use this macro, remember to undef it at the end of this header by `#undef X`

2022-11-29 07:28 UTC, EYH0602 commented on encode2stdout.h
> +            char pfmt[10] = "%s,%c,%";                \
so `std::string` in this case? I think we should use C++ string for other sting operations as well

2022-11-29 08:04 UTC, DataCorrupted commented on encode2stdout.h
> +            char pfmt[10] = "%s,%c,%";                \
In this particular case `pfmt` maybe not. Sorry I just realize it will be used in `scanf`, using `std::string` may cause touble.
But when you are trying to find types (`%d`), I thing using `std::string` and `std::regex` may help. Its up to you.

2022-11-30 00:43 UTC, EYH0602 commented on encode2stdout.h
> +                type_tokens[idx] = fmt[i + 1];                                        \
checked all, no \% or %% case found

2022-11-30 01:08 UTC, EYH0602 commented
```
1 2
&a,f,1.000000
&b,d,2
3
c,,3
```

currently `SCANF_ALT` will also print a `&` in front of variable name since `scanf` takes in reference. Should this `&` be removed?

2022-11-30 01:54 UTC, DataCorrupted approved these changes

2022-11-30 01:54 UTC, DataCorrupted commented on encode_example.cpp
> +    SCANF_ALT("%f %d", &a, &b);
Would be nice to add more testcases.
- Different types(`string`, `int`, `double`, etc.)
- Different pointers(`&a`, `a_ptr`, `a_ptr + 2`)

2022-11-30 01:54 UTC, DataCorrupted commented on encode_example.cpp
> +    CIN(c);
More tests here too. 
Also did you include a script that does `cin << x` to `CIN(x)` conversion?

2022-11-30 02:34 UTC, DataCorrupted commented
> ```
> 1 2
> &a,f,1.000000
> &b,d,2
> 3
> c,,3
> ```
> 
> currently `SCANF_ALT` will also print a `&` in front of variable name since `scanf` takes in reference. Should this `&` be removed?

I talked to backend guys yesterday, they said its fine to keep them "as is"

2022-11-30 03:27 UTC, EYH0602 commented on encode_example.cpp
> +    CIN(c);
👌🏻

2022-11-30 19:09 UTC, EYH0602 commented on encode_example.cpp
> +    SCANF_ALT("%f %d", &a, &b);
```
SCANF_ALT: float and int separate by space
1 2
&a,f,1.000000
&b,d,2
SCANF_ALT: char and string separate by comma
o,abc
&c,c,o
d,s,abc
SCANF_ALT: char as ptr+2
d
str+2,c,d
SCANF_ALT: long
1000861234
&li_var,ld,1000861234
SCANF_ALT: ptr_var to short (enter short int)
1
ptr_var,hd,1
```

2022-11-30 19:10 UTC, EYH0602 commented on encode_example.cpp
> +    CIN(c);
```
CIN int
1
e,,1
CIN float
3.14
f,,3.14
CIN char
o
g,,o
CIN string
abc
h,,abc
```

2022-11-30 19:10 UTC, merged